apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory-service
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  strategy: {}
  template:
    metadata:

      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: artkhud20/inventory-service:1.0.0
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-inventory:5732/storehousedb
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: eureka.instance.preferIpAddress
              value: "true"
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-service
  name: inventory-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 9191
  selector:
    app: inventory-service
status:
  loadBalancer: {}