apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-product
  name: postgres-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product
  template:
    metadata:
      labels:
        app: postgres-product
    spec:
      containers:
        - name: postgres-product
          image: postgres:15
          args:
            - "-p"
            - "5734"
          env:
            - name: PGDATA
              value: /data/postgres
            - name: POSTGRES_DB
              value: storehousedb
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: user
          ports:
            - containerPort: 5734
          resources: {}
          volumeMounts:
            - mountPath: /data/postgres
              name: postgres-product1-claim0
      restartPolicy: Always
      volumes:
        - name: postgres-product1-claim0
          persistentVolumeClaim:
            claimName: postgres-product1-claim0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-product
  name: postgres-product
spec:
  ports:
    - name: "5734"
      port: 5734
      targetPort: 5734
  selector:
    app: postgres-product
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-product1-claim0
  name: postgres-product1-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}