apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  strategy: {}
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: artkhud20/product-service:2.0.0
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-product:5734/storehousedb
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: eureka.instance.preferIpAddress
              value: "true"

      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-service
  name: product-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    app: product-service
status:
  loadBalancer: {}